# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 09:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('notes', models.TextField(default='')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('reading_status', models.PositiveSmallIntegerField(choices=[(0, 'Unstarted'), (1, 'Started'), (2, 'Finished')], default=0)),
            ],
        ),
    ]
